# Generated by Django 4.1 on 2022-09-03 22:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nick', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propia', models.CharField(max_length=300)),
                ('extranjera', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Frase',
                'verbose_name_plural': 'Frases',
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero', models.FileField(null=True, upload_to='logos', verbose_name='Logo')),
                ('idioma', models.CharField(choices=[('en', 'English'), ('en-au', 'English (Australia)'), ('en-uk', 'English (United Kingdom)'), ('en-us', 'English (United States)'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('es-es', 'Spanish (Spain)'), ('es-us', 'Spanish (United States)')], default='en', max_length=6)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('res_external', models.CharField(blank=True, max_length=100, null=True, verbose_name='Url youtube')),
                ('nota', models.TextField(blank=True)),
                ('fichero', models.FileField(blank=True, null=True, upload_to='final_leccion')),
                ('tipo', models.CharField(choices=[('VD', 'Video'), ('SN', 'Sonido'), ('EX', 'Youtube')], default='EX', max_length=2)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Pronunciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero', models.FileField(null=True, upload_to='pronuciacion')),
                ('tipo', models.CharField(choices=[('VD', 'Video'), ('SN', 'Sonido')], default='SN', max_length=2)),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.frases')),
            ],
            options={
                'verbose_name': 'Pronuciacion',
                'verbose_name_plural': 'Pronuciaciones',
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.estudiante')),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.frases')),
            ],
        ),
        migrations.CreateModel(
            name='Lecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo', models.TextField(default='')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.cursos')),
                ('recursos', models.ManyToManyField(blank=True, to='idiomatic.recursos')),
            ],
            options={
                'verbose_name': 'Leccion',
                'verbose_name_plural': 'Lecciones',
            },
        ),
        migrations.CreateModel(
            name='Helpers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_file', models.ImageField(null=True, upload_to='helpers')),
                ('helper_str', models.TextField(null=True)),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.frases')),
            ],
            options={
                'verbose_name': 'Helper',
                'verbose_name_plural': 'Helpers',
            },
        ),
        migrations.AddField(
            model_name='frases',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.lecciones'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.idiomas'),
        ),
    ]
