# Generated by Django 2.0.4 on 2018-04-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propia', models.CharField(max_length=200)),
                ('extranjera', models.CharField(max_length=200)),
                ('positivos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Frase',
                'verbose_name_plural': 'Frases',
            },
        ),
        migrations.CreateModel(
            name='Helpers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_file', models.ImageField(null=True, upload_to='helpers')),
                ('helper_str', models.TextField(null=True)),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.Frases')),
            ],
            options={
                'verbose_name': 'Helper',
                'verbose_name_plural': 'Helpers',
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='logos')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Lecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('objetivo', models.TextField(default='')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.Cursos')),
            ],
            options={
                'verbose_name': 'Leccion',
                'verbose_name_plural': 'Lecciones',
            },
        ),
        migrations.CreateModel(
            name='Pronunciacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronunciacion', models.FileField(null=True, upload_to='pronuciacion')),
                ('tipo', models.CharField(choices=[('VD', 'Video'), ('SN', 'Sonido')], default='SN', max_length=2)),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.Frases')),
            ],
            options={
                'verbose_name': 'Pronuciacion',
                'verbose_name_plural': 'Pronuciaciones',
            },
        ),
        migrations.AddField(
            model_name='frases',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.Lecciones'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='idioma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.Idiomas'),
        ),
    ]
