# Generated by Django 2.0.4 on 2018-04-10 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idiomatic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=uuid.uuid4, max_length=100)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='frases',
            name='positivos',
        ),
        migrations.RemoveField(
            model_name='idiomas',
            name='nombre',
        ),
        migrations.AddField(
            model_name='idiomas',
            name='idioma',
            field=models.CharField(choices=[('en', 'English'), ('en-au', 'English (Australia)'), ('en-uk', 'English (United Kingdom)'), ('en-us', 'English (United States)'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('es-es', 'Spanish (Spain)'), ('es-us', 'Spanish (United States)')], default='en', max_length=4),
        ),
        migrations.AddField(
            model_name='progreso',
            name='frase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.Frases'),
        ),
    ]
