# Generated by Django 2.0.4 on 2018-04-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idiomatic', '0002_auto_20180410_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progreso',
            old_name='codigo',
            new_name='estudiante',
        ),
    ]
