# Generated by Django 2.0.4 on 2018-04-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idiomatic', '0003_auto_20180410_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalLeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero', models.FileField(null=True, upload_to='pronuciacion')),
                ('tipo', models.CharField(choices=[('VD', 'Video'), ('SN', 'Sonido')], default='SN', max_length=2)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.Lecciones')),
            ],
        ),
        migrations.AlterField(
            model_name='idiomas',
            name='idioma',
            field=models.CharField(choices=[('en', 'English'), ('en-au', 'English (Australia)'), ('en-uk', 'English (United Kingdom)'), ('en-us', 'English (United States)'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('es-es', 'Spanish (Spain)'), ('es-us', 'Spanish (United States)')], default='en', max_length=6),
        ),
    ]
