# Generated by Django 2.0.4 on 2018-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idiomatic', '0004_auto_20180415_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nota', models.TextField()),
                ('fichero', models.FileField(null=True, upload_to='final_leccion')),
                ('tipo', models.CharField(choices=[('VD', 'Video'), ('SN', 'Sonido')], default='SN', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='finalleccion',
            name='leccion',
        ),
        migrations.RenameField(
            model_name='pronunciacion',
            old_name='pronunciacion',
            new_name='fichero',
        ),
        migrations.RemoveField(
            model_name='idiomas',
            name='logo',
        ),
        migrations.AddField(
            model_name='idiomas',
            name='fichero',
            field=models.FileField(null=True, upload_to='logos', verbose_name='Logo'),
        ),
        migrations.DeleteModel(
            name='FinalLeccion',
        ),
        migrations.AddField(
            model_name='lecciones',
            name='recursos',
            field=models.ManyToManyField(to='idiomatic.Recursos'),
        ),
    ]
