# Generated by Django 2.2.6 on 2020-02-16 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idiomatic', '0006_auto_20180419_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nick', models.CharField(max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='frases',
            name='extranjera',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='frases',
            name='propia',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lecciones',
            name='recursos',
            field=models.ManyToManyField(blank=True, to='idiomatic.Recursos'),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idiomatic.Estudiante'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='fichero',
            field=models.FileField(blank=True, null=True, upload_to='final_leccion'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='nota',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='res_external',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url youtube'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='tipo',
            field=models.CharField(choices=[('VD', 'Video'), ('SN', 'Sonido'), ('EX', 'Youtube')], default='EX', max_length=2),
        ),
    ]
